[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200

[[redirects]]
  from = "/api/settings/bulk"
  to = "/.netlify/functions/settings-bulk"
  status = 200

[[redirects]]
  from = "/api/settings/*"
  to = "/.netlify/functions/settings/:splat"
  status = 200

[[redirects]]
  from = "/api/projects/*"
  to = "/.netlify/functions/projects/:splat"
  status = 200

[[redirects]]
  from = "/api/projects"
  to = "/.netlify/functions/projects"
  status = 200

[[redirects]]
  from = "/api/settings"
  to = "/.netlify/functions/settings"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
